import "./globals.css";
import "./fanta.css";
import Head from "./head";
import AuthPovider from "@/context/AuthContext";

export const metadata = {
  title: "MyNotes | Easy NoteTaking",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  const { children } = props;
  return (
    <html lang="en">
      <Head />
      <AuthPovider>
        <body>
          <div id="app">{children}</div>
          <div id="portal"></div>
        </body>
      </AuthPovider>
    </html>
  );
}
